### ISSUE TITLE
[BUG] 댓글 삭제 시 반응 없음

### ISSUE THREAD

**Issue by d3pshot17** [wafflestudio19-5/team10-web#48]
댓글을 삭제하면 바로 반영되지 않고 새로고침을 해야 반영이 됩니다!
![comment](https://user-images.githubusercontent.com/83637115/148634008-1ed7e8ee-6713-4670-9a98-4697e3c942de.png)

**Comment by andhl204** [comment]
감사합니다! 고쳐서 배포했습니다:)
