### ISSUE TITLE
[BUG] 프로필의 음악에서 댓글 작성시 반응 없음

### ISSUE THREAD

**Issue by yg-moon** [wafflestudio19-5/team10-web#49]
<img width="882" alt="Screen Shot 2022-01-08 at 3 20 42 PM" src="https://user-images.githubusercontent.com/56223439/148634069-2b715a9f-6aba-4315-b2f9-912b93766eba.png">

위 화면에서 댓글을 작성해도 아무 반응이 없습니다.

**Comment by hmlinnie** [comment]
댓글 작성칸 placeholder에 엔터키를 누르라는 문구를 추가하고, 댓글 작성 시 "댓글 작성 완료" toast가 뜨도록 변경했습니다.
피드백 감사합니다!! :)
