### ISSUE TITLE
[BUG] 프로필 화면에서 트랙 클릭시 없는 음악이라고 나옵니다.

### ISSUE THREAD

**Issue by yg-moon** [wafflestudio19-5/team10-web#50]
<img width="1255" alt="Screen Shot 2022-01-08 at 3 22 48 PM" src="https://user-images.githubusercontent.com/56223439/148634097-885b197e-28b7-419f-b0d6-79b786b44116.png">

이렇게 나옵니다

**Comment by hmlinnie** [comment]
아직 profile-track페이지가 구현되지 않은 상태에서 해당 url이 다른 페이지(track이라는 제목을 가진 노래 페이지)로 인식된 것 같습니다.
현재 버튼을 눌러도 페이지가 이동되지 않게 변경하였고, 해당 페이지 구현 후 다시 제대로 연결하도록 하겠습니다!
피드백 감사합니다 :)
