### ISSUE TITLE
[BUG] 회원가입 에러 피드백

### ISSUE THREAD

**Issue by wallabyg** [wafflestudio19-5/team10-web#51]
## 현재 동작
유효하지 않은 정보(음수 나이, 이름 빈 문자열)로 회원가입 시도 시 서버에서 400 response는 오는데, 뒤로 가기나 정보 재입력이 불가능합니다.

화면의 다른 곳을 클릭한 뒤 다시 시도하면 display name 설정으로 돌아와서 새로고침 전까지 회원가입 시도가 계속 실패합니다.

**Comment by Arsture** [comment]
그렇네요,,, 알려주셔서 감사합니다!!
해결하겠습니당 👍
