### ISSUE TITLE
[BUG] 메인페이지에서 좋아요를 누르면 새로고침해야 반영됩니다.

### ISSUE THREAD

**Issue by kmsgm** [wafflestudio19-5/team10-web#52]
![image](https://user-images.githubusercontent.com/49176503/148634191-e439e17c-8ba6-4aea-83ed-affa89716d59.png)

좋아요를 누르면 바로 반영되는 것이 아니라 새로고침해야 옆에 뜹니다.

(+) 버그는 아니지만 옆에 좋아용 리스트 앨범 사진과 옆의 글 내용 사이의 간격이 있으면 좋을 것 같습니다.

**Comment by kmsgm** [comment]
좋아요 리스트에서 좋아요를 해제할 때도 마찬가지로 새로고침해야 반영됩니다

**Comment by Arsture** [comment]
넵, 좋아요 후 좋아요 list를 업데이트 하지 않아서 그렇습니다!

알려주셔서 감사합니다, 고치도록 하겠습니다 👍 

간격은 제가 default image size를 조정안했네요 ㅠㅠ 알려주셔서 감사합니당
