### ISSUE TITLE
[BUG] Likes 페이지에서 새로고침시 이미지와 트랙이 보이지 않습니다.

### ISSUE THREAD

**Issue by yjeong-k** [wafflestudio19-5/team10-web#54]
안녕하세요! 
Likes 페이지에서 새로고침을 하였을 때, 프로필 이미지와 트랙정보들이 보이지 않는 것 같습니다. 아래 사진을 첨부합니다.
실제 사운드 클라우드와 엄청 비슷하게 잘 구현해주셔서 정말 잘 보았습니다. 중간총회까지 너무 고생많으셨습니다!☺️

1. Likes 탭에 들어갔을 때
![image](https://user-images.githubusercontent.com/65206075/148634678-019c5e3f-98f0-4965-ab16-a659b9f0f54c.png)

2. Likes 탭에서 새로고침을 하였을 때
![image](https://user-images.githubusercontent.com/65206075/148634710-d943031d-2cf1-4dda-b0a4-600189642f6f.png)

감사합니다 :)

**Comment by Arsture** [comment]
알려주셔서 감사합니다! 고쳤습니다 :)

(배포는 안해서 적용 안됐을겁니당)
