### ISSUE TITLE
[BUG] 프로필 페이지에서 중단탭 클릭시 우상단 프로필 사진 표시 안되는 에러

### ISSUE THREAD

**Issue by HyeongtaekOh** [wafflestudio19-5/team10-web#56]
프로필 페이지에서 중단탭(All, Popular Tracks, Tracks, 등등) 클릭해서 페이지 넘어가면 우상단에 닉네임 왼쪽에 표시되는 프로필 이미지가 대체 텍스트로 나옵니다.

**Comment by hmlinnie** [comment]
링크만 걸어놓고 아직 페이지를 구현하지 않아 생긴 문제인 것 같습니다.
현재 버튼을 눌러도 페이지 이동이 안되게끔 변경하였고, 페이지 구현 후 다시 제대로 연결하도록 하겠습니다!
피드백 감사합니다 :)
