### ISSUE TITLE
[Bug] 사용자 이름이 너무 길면 상단 바에서 벗어납니다.

### ISSUE THREAD

**Issue by joongwon** [wafflestudio19-5/team10-web#57]
![image](https://user-images.githubusercontent.com/46706963/148634962-a47b9e94-7165-44da-8f1e-858981ad631d.png)
Google 계정으로 로그인했을 때 사용자 이름이 너무 길면 상단 바에서 이름이 벗어납니다.
또, 프로필 사진도 상단바를 벗어나게 됩니다.

**Comment by hmlinnie** [comment]
사용자 이름이 길더라도 상단바에서 벗어나지 않도록 css 수정하였습니다!
피드백 감사합니다 :)
