### ISSUE TITLE
[Bug] 프로필 페이지에서 share을 눌렀을 때 반응이 없습니다.

### ISSUE THREAD

**Issue by padme0421** [wafflestudio19-5/team10-web#58]
유저 프로필 페이지에서 share 버튼을 눌렀을 때 반응이 없습니다.

**Comment by hmlinnie** [comment]
아직 구현하지 못한 기능인데, 혼란을 드려 죄송합니다.
구현 전까지 버튼이 보이지 않도록 수정하였습니다!
피드백 감사합니다 :)
