### ISSUE TITLE
[BUG] 프로필 업데이트 시 우측 상단 사용자 이름 업데이트 문제

### ISSUE THREAD

**Issue by HyungGeun-Cho** [wafflestudio19-5/team10-web#59]
프로필 유저 이름 업데이트 시 우측 상단 사용자 이름이 바로 업데이트 되지 않고
한번 새로고침을 해야 업데이트되는 것 같습니다!
<br/>
<img width="1440" alt="스크린샷 2022-01-08 오후 4 03 25" src="https://user-images.githubusercontent.com/78595247/148635212-296b80e5-0bdb-4fb9-b290-28f02accac3d.png">

**Comment by hmlinnie** [comment]
미처 고려하지 못한 부분이네요.
프로필 유저 정보 업데이트시 헤더바에도 바로 반영되도록 수정하였습니다!
피드백 감사합니다 :)
