### ISSUE TITLE
[BUG] 앨범 커버 및 프로필 글자 관련버그

### ISSUE THREAD

**Issue by ChrisLee02** [wafflestudio19-5/team10-web#60]
1. 앨범 커버에서 재생하는 것이 동작을 안 합니다.
2. 프로필 글자가 줄바꿈되는 현상 + 흰 글자라서 배경에 묻힙니다.

**Comment by HunRotation** [comment]
![image](https://user-images.githubusercontent.com/48827296/148638106-defe9911-e366-4647-beb9-5d81fb696206.png)
![image](https://user-images.githubusercontent.com/48827296/148638185-bd2b7c2b-2726-4766-80d9-c4638b938b5c.png)

덧붙이자면 위 이미지처럼 Home 화면에서 앨범 이미지를 클릭했을 때 밑에 재생 component가 뜨지 않고, 이미 다른 음악을 재생 중일 때 다른 앨범 이미지를 클릭할 때도 이미지에 재생 표시는 뜨는데 실제 재생에 영향이 없습니다!

**Comment by Arsture** [comment]
첫 번째 버그는, 미구현 상태여서 안됐을 겁니다! 배포하진 않았지만 해당 기능 구현 완료하였습니다 😀

**Comment by hmlinnie** [comment]
두 번째 버그도 프로필 이름에 따라 상단바 너비가 조정되도록 수정하였습니다.
피드백 감사합니다! :)
