### ISSUE TITLE
[BUG] 프로필, 배너 이미지 업로드를 비롯한 프로필 변경 문제들

### ISSUE THREAD

**Issue by jm020827** [wafflestudio19-5/team10-web#61]
1. 배너 이미지, 프로필 이미지를 업로드해도 한번에 갱신되지 않고 한번 새로고침을 통해 리렌더 해야 변경 확인이 가능합니다.

2. 배너 이미지 비율이 고정되어 있어 이미지를 직접 자를 수 있거나 어느 한쪽에 맞춰 자동으로 잘리지도 않고 찌부가 되어 배너에 들어가 그 배너 화면 비율에 딱 맞는 사진을 넣어야만 원하는대로 배너 이미지를 채울 수 있습니다.

3. 프로필에서 Edit을 눌러서 뜨는 모달에서 변경사항들이 반영이 안되어 모달을 닫았다가 열었음에도 모달에 입력/ 업로드했던 정보/사진들은 그대로 남아있는 버그가 존재합니다. 

4. 프로필 변경 실패 시 그 이유를 사용자가 알기 힘듭니다.

**Comment by hmlinnie** [comment]
1. 프로필 / 헤더 이미지를 변경할 경우 변경사항이 바로 적용되도록 수정하였습니다.
2. 업로드 전 이미지를 수정할 수 있는 프로그램 추가를 고려해보고 있습니다!
3. Cancel 버튼을 누를 경우 입력값이 초기화되도록 버그 수정하였습니다.
4. 에러 메시지를 세분화시키도록 하겠습니다.

자세한 피드백 감사합니다!! :) 큰 도움이 되었어요!
