### ISSUE TITLE
[BUG] 메인 홈 화면에서 재생 버튼을 눌렀음에도 재생이 되지 않는 문제

### ISSUE THREAD

**Issue by jm020827** [wafflestudio19-5/team10-web#62]
제가 사운드 클라우드를 안써봐서 혹시 의도된 기능이라면 무시하셔도 되는 문제입니다!

홈화면에서 각 음악들을 호버했을 때 뜨는 재생 버튼을 클릭해도 아무 변화 없이 원래 재생되던 음악이 계속 재생됩니다. 또한 여러 음악에 대해 그렇게 재생버튼을 모두 눌러두면, 눌러준 모든 음악들이 그 상태로 동시에 존재할 수 있다는 문제점이 있습니다.

**Comment by Arsture** [comment]
넵 해당 기능은 미구현 상태였습니다. 배포되진 않았지만 해당 기능 구현 완료하였습니다. 피드백 감사드립니다 😀
