### ISSUE TITLE
[Bug] 사파리 브라우저에서의 재생 오류

### ISSUE THREAD

**Issue by yabsed** [wafflestudio19-5/team10-web#64]
https://youtu.be/Q6BXSNfAYQw

M1 Macbook Air로 테스트
Vivaldi(Google Chrome)에서는 음악 정상 재생됨
하지만 Safari 브라우저에서는 하얀 화면과 함께 튕김

**Comment by andhl204** [comment]
생각하지 못했던 부분인데 다양한 브라우저로 시도해 보시고 문제점을 자세하게 보여주셔서 정말 감사합니다! 사파리에서도 정상적으로 작동하도록 바꾸었습니다.
