### ISSUE TITLE
[Bug] 동시재생

### ISSUE THREAD

**Issue by yabsed** [wafflestudio19-5/team10-web#65]
https://youtu.be/_t6WN_mIBZE

특정 계정의 프로필에서 재생 버튼을 누르면
다양한 음악이 동시에 재생됩니다

되게 잘 만드신 것 같아요 😍

**Comment by hmlinnie** [comment]
동시재생의 문제가 있었네요!!
프로필 페이지에서 노래가 동시 재생되지 않도록 (이전에 재생되던 노래가 멈추도록) 변경하였습니다.
자세한 피드백 감사합니다!! :)
