### ISSUE TITLE
[Bug] 프로필에서 popular track 선택 시 UI 깨짐 오류

### ISSUE THREAD

**Issue by chaemin2001** [wafflestudio19-5/team10-web#66]
아직 구현 안하신 부분일 수도 있지만 느낌표 등 UI가 깨져 보이는 현상이 나타나는 것 같습니다! 수정하면 훨씬 보기 좋을 듯해요

**Comment by hmlinnie** [comment]
피드백 반영하여 구현되지 않은 페이지의 경우 클릭이 불가능하도록 수정해놓았습니다!
피드백 감사합니다 :)
