### ISSUE TITLE
[BUG] 음악 Upload 관련 issue

### ISSUE THREAD

**Issue by s-yeoyul** [wafflestudio19-5/team10-web#67]
![스크린샷, 2022-01-08 22-08-32](https://user-images.githubusercontent.com/81800659/148645434-016dc6ca-2aaa-4e5e-895a-b62e20ebc040.png)
- 일단 음악을 업로드하려 하면 POST 할때 401 Unauthorized를 보냅니다
- public(default)인데 defualt로 오타가 난 것 같습니다
- Save버튼을 누르면 트랙 url을 변경해달라, 업로드가 실패했다는 toast를 띄우는데 Cancel 버튼을 누르면 아무 일도 일어나지 않습니다!

**Comment by hmlinnie** [comment]
1. 기존에 토큰을 제대로 받아오지 못하는 문제가 있었던 것 같습니다. 토큰 가져오는 방법을 변경하여 업로드가 잘 되도록 조치했습니다.
2. 오타 수정했습니다.
3. cancel 버튼에 기능이 빠져있는 걸 미처 확인하지 못했네요. 기능 추가했습니다.

자세한 피드백 정말 감사합니다! :)
