### ISSUE TITLE
[BUG] Notification 불러오기 오류

### ISSUE THREAD

**Issue by devpotatopotato** [wafflestudio19-5/team10-web#69]
회원가입한 직후 Notification으로 접속하면 정보 불러오기 실패라고 나옵니다.

오류 발생 시 오류 창을 띄우는 것도 나쁘지 않을 것 같아요!

**Comment by hmlinnie** [comment]
아직 구현하지 못한 페이지인데, 혼동을 드려 죄송합니다.
구현하지 않은 페이지의 경우 버튼을 눌러도 이동되지 않도록 조치하였습니다.
피드백 감사합니다! :)
