### ISSUE TITLE
[BUG] 나이를 -2로 설정한 경우

### ISSUE THREAD

**Issue by jaejae2374** [wafflestudio19-5/team10-web#71]
나이를 -2로 설정했더니 별도의 오류메시지 없이 넘어가진 다음, GET STARTED를 눌렀을 시 다음페이지로 진행이 안됩니다.

![image](https://user-images.githubusercontent.com/80879249/148688263-8110b647-4005-416a-8f1b-608f17c19892.png)

**Comment by Arsture** [comment]
넵, 고쳤습니다!
