### ISSUE TITLE
[BUG] 아무 내용이 없는 댓글 무한 작성 가능

### ISSUE THREAD

**Issue by jaejae2374** [wafflestudio19-5/team10-web#72]
댓글 작성할 때 엔터만 계속 누르면, 아무 내용 없는 댓글을 무한으로 작성 가능한데, 원래 사운드 클라우드에서도 그런가요...? 보통 댓글 같은거 달 때 한글자 이상이라도 내용이 있는지 체크해야 되지 않나 싶은 생각이 듭니다...
엔터를 꾹 눌렀더니 300개를 5초안에 달아버렸습니다..
![image](https://user-images.githubusercontent.com/80879249/148688562-2d7d5404-827f-4be9-8775-697606558843.png)

**Comment by andhl204** [comment]
아무 내용도 없는 댓글 작성 시(스페이스바만 누르는 등) 작성(submit)되지 않도록 하고, 짧은 시간에 여러 번 작성할 수 없도록 고쳤습니다. 감사합니다!
